# BRODCASTING IN NUMPY

In [4]:
import numpy as np
#Erstellen eines Arrays
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [13]:
#we will loop +10
arr1 + 10

array([10, 11, 12, 13, 14])

In [15]:
#we will loop /5
arr1/5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [16]:
#we will loop **2
arr1**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [10]:
arr2 = np.arange(15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
#we will loop +5
arr2+5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
#dplicatet 3times (3REIHERN/3ZEILEN) jedes mit jedem
arr1 + arr2

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [21]:
v1=np.arange(3)
v1

array([0, 1, 2])

In [23]:
v2=np.arange(3).reshape((3,1))
v2

array([[0],
       [1],
       [2]])

In [25]:
#logik verstehen v1 wird mit jeder zeile von v2 addiert
v1+v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [28]:
print(np.arange(5))
print(np.arange(3))

[0 1 2 3 4]
[0 1 2]


In [32]:
#BEWUSSTER FEHLER ADDITION IST HIER NICHT ERLAUBT weil SPALTEN ANZAHL NICHT MIT ZEILENANZAHL UEBEREINSTIMMT
np.arange(5)+np.arange(3)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [34]:
np.arange(15).reshape(3,5)+np.arange(5)

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [39]:
print(np.arange(3)+np.arange(3).reshape(3,1))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [1]:
## QUELLE: https://www.youtube.com/watch?v=tuKHsfAehz4