# Einführung Numpy

In [2]:
import numpy as np

In [3]:
#python liste
meine_liste = [1,2,3]

In [5]:
meine_liste

[1, 2, 3]

In [7]:
#numpy array erstellen
np.array(meine_liste)

array([1, 2, 3])

In [9]:
#numpy matrix erstellen
matrix=[[1,2,3],[4,5,6]]

In [11]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [13]:
#wieder als numpy array konvertieren
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#von eins bis 10
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
#null werte erstellen in array
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
#array in der dimension 5x5
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [28]:
#matrix der dimension 3x3 mit einser values
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
#startwert, endwert,anzahl werte
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [34]:
#startwert, endwert,default wert ist 50
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [36]:
#einheitsmatrix der dimension 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
#zufallszahl in array
np.random.rand(2)

array([0.99561291, 0.55761739])

In [40]:
#zufalswert in matrix 5x5
np.random.rand(5,5)

array([[0.27380732, 0.92496532, 0.53618129, 0.9833996 , 0.36084677],
       [0.36956628, 0.96934662, 0.81875646, 0.38360953, 0.1793633 ],
       [0.0295469 , 0.02501429, 0.33203401, 0.7397901 , 0.23481243],
       [0.6508311 , 0.00222855, 0.47100926, 0.68463161, 0.48298826],
       [0.55602627, 0.63501978, 0.94254533, 0.57931381, 0.02583046]])

In [42]:
#int zufallszahl
np.random.randint(1,100)

58

In [44]:
#int zufallszahl, anzahl
np.random.randint(1,100,10)

array([71, 13, 92,  8,  7, 49, 33, 75, 79, 51])

In [47]:
arr = np.arange(25)

In [49]:
ranarr = np.random.randint(0,50,10)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr

array([ 3, 49,  8, 12, 14,  1, 31, 15, 16, 44])

In [56]:
#umgewandelte Matrize aus array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
ranarr.max()

49

In [61]:
#position der größten zahl
ranarr.argmax()

1

In [63]:
ranarr.min()

1

In [65]:
ranarr.argmin()

5

In [68]:
#10 = eindimensional mit 10 attributen
arr.shape

(25,)

In [70]:
ranarr.shape

(10,)

In [72]:
#datentyp ausgeben
arr.dtype

dtype('int32')

# Numpy Array Indexing

In [77]:
#array erstellen
arr = np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
#index aus einem array auslesen
arr[8]

8

In [81]:
#wertebereich
arr[1:5]

array([1, 2, 3, 4])

In [84]:
#numpy broadcasting
arr[0:5]=100

In [87]:
#die ersten 5 werte haben den wert 100 bekommen
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [89]:
arr = np.arange(0,11)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
teil_arr=arr[0:6]

In [95]:
teil_arr

array([0, 1, 2, 3, 4, 5])

In [97]:
#alle werte indem Bereich haben den wert 99 bekommen
teil_arr[:]=99

In [99]:
teil_arr

array([99, 99, 99, 99, 99, 99])

In [102]:
#array kopieren um keine Änderungen auf dem original array durchzuführen
arr_kopie=arr.copy()

In [104]:
arr_kopie

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [106]:
#2d arrays anschauen
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [108]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
#erste reihe zurückgeben
arr_2d[1]

array([20, 25, 30])

In [113]:
#2 reihe erstes element
arr_2d[1][0]

20

In [115]:
arr_2d[0,1]

10

In [117]:
#ersten zwei reihen ausgeben
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [121]:
#bis zur zweiten spalte (ersten beiden reihen) und von 1 (zweitens) bis ende zahlen
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [123]:
arr_2d[2,:]

array([35, 40, 45])

In [125]:
arr = np.arange(1,11)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
#vergleich innerhalb eines array als array
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [132]:
#das ganze kann man absspeichern
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [134]:
#wenn bedingung erfüllt ist ausgabe der daten
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [136]:
#wenn bedingung erfüllt ist ausgabe der daten
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [139]:
#verleich mit einer variable verglichen
x=2
arr[arr<x]

array([1])

In [143]:
#arrange 2d erstellen zahlen bis 50 dimension 5x10
arr_2d=np.arange(50).reshape(50).reshape(5,10)

In [145]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [147]:
#wertebereich zur ausgabe ausgeben reihen
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [149]:
#wertebereich zur ausgabe ausgeben reihen + jeweils von 4 bis 5 in den reihen
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operationen

## universelle Array Funktionen

In [153]:
# Die Quadratwurzel ziehen
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [155]:
# den Exponent (^e) berechnen
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [161]:
# das gleich wie arr.max()
np.max(arr)

10

In [163]:
#sinus
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [165]:
#logaritmus
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

## Operationen

In [180]:
arr = np.arange(0,10)

In [181]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [174]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [176]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [182]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [184]:
#ergebnis sind unendlich lang
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [185]:
arr**arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [187]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [189]:
#quadratwurzel
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [191]:
#mit e gekürzt
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [193]:
np.max(arr)

9

In [195]:
arr.max()

9

In [198]:
#sinus
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [201]:
#logaritmus
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [202]:
# weitere Informationen unter scipy.org